name: fint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - netcdf4
  - xarray
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pip
  - cartopy
  - shapely
  - cdo
  - pip:
    - smmregrid
    

