name: fint shell test

# Controls when the action will run. Triggers the workflow on push or pull request. 

on: [push]


jobs:
  fint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: provision-with-micromamba
      uses: mamba-org/provision-with-micromamba@v11

    - name: Run tests
        shell: bash -l {0}
        run: |
          ./tests.sh
